Fixed bugs MissingComponentException: There is no 'Rigidbody2D' attached to the "Ground" game object...
MissingComponentException: There is no 'Rigidbody2D' attached to the "Ground" game object, but a script is trying to access it.
You probably need to add a Rigidbody2D to the game object "Ground". Or your script needs to check if the component is attached before using it.
UnityEngine.Object+MarshalledUnityObject.TryThrowEditorNullExceptionObject (UnityEngine.Object unityObj, System.String parameterName) (at <6b66e7caaeb045048a0fbc11f111e6fa>:0)
UnityEngine.Bindings.ThrowHelper.ThrowNullReferenceException (System.Object obj) (at <6b66e7caaeb045048a0fbc11f111e6fa>:0)
UnityEngine.Rigidbody2D.get_velocity () (at <c03889a4b4984101a827b6573211d699>:0)
WaterWaves2D.OnTriggerExit2D (UnityEngine.Collider2D other) (at Assets/WaterWaves2D/Script/WaterWaves2D.cs:372)